services:

  kafka:
    image: apache/kafka:4.0.0
    container_name: tiffin-kafka
    ports:
      - "9092:9092"
    mem_limit: 320m
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_HEAP_OPTS: "-Xmx220m -Xms220m"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: tiffin-kafka-ui
    profiles: ["debug"]
    ports:
      - "8090:8080"
    depends_on:
      - kafka
    mem_limit: 100m
    environment:
      KAFKA_CLUSTERS_0_NAME: biteloop-local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  redis:
    image: redis:7.2-alpine
    container_name: tiffin-redis
    ports:
      - "6379:6379"
    mem_limit: 60m
    restart: unless-stopped

  api-gateway:
    image: 980819806799.dkr.ecr.ap-south-1.amazonaws.com/biteloop-api-gateway:latest
    container_name: tiffin-api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - .env
    mem_limit: 220m
    restart: unless-stopped
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JAVA_TOOL_OPTIONS: "-Xmx150m -Xss256k"

  user-service:
    image: 980819806799.dkr.ecr.ap-south-1.amazonaws.com/biteloop-user-service:latest
    container_name: tiffin-user-service
    ports:
      - "8081:8081"
    depends_on:
      - kafka
    env_file:
      - .env
    mem_limit: 180m
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: ${USER_SERVICE_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      JWT_SECRET: ${JWT_SECRET}
      JAVA_TOOL_OPTIONS: "-Xmx130m -Xss256k"

  provider-service:
    image: 980819806799.dkr.ecr.ap-south-1.amazonaws.com/biteloop-provider-service:latest
    container_name: tiffin-provider-service
    ports:
      - "8082:8082"
    depends_on:
      - kafka
    env_file:
      - .env
    mem_limit: 180m
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: ${PROVIDER_SERVICE_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      JWT_SECRET: ${JWT_SECRET}
      USER_SERVICE_URL: http://user-service:8081
      JAVA_TOOL_OPTIONS: "-Xmx130m -Xss256k"

  menu-service:
    image: 980819806799.dkr.ecr.ap-south-1.amazonaws.com/biteloop-menu-service:latest
    container_name: tiffin-menu-service
    ports:
      - "8083:8083"
    depends_on:
      - redis
    env_file:
      - .env
    mem_limit: 180m
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: ${MENU_SERVICE_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT}
      JAVA_TOOL_OPTIONS: "-Xmx130m -Xss256k"

  order-service:
    image: 980819806799.dkr.ecr.ap-south-1.amazonaws.com/biteloop-order-service:latest
    container_name: tiffin-order-service
    ports:
      - "8084:8084"
    depends_on:
      - kafka
      - redis
    env_file:
      - .env
    mem_limit: 190m
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: ${ORDER_SERVICE_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JAVA_TOOL_OPTIONS: "-Xmx140m -Xss256k"

  payment-service:
    image: 980819806799.dkr.ecr.ap-south-1.amazonaws.com/biteloop-payment-service:latest
    container_name: tiffin-payment-service
    ports:
      - "8086:8086"
    depends_on:
      - kafka
    env_file:
      - .env
    mem_limit: 180m
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: ${PAYMENT_SERVICE_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      key-id: ${RAZORPAY_KEY_ID}
      key-secret: ${RAZORPAY_KEY_SECRET}
      webhook-secret: ${RAZORPAY_WEBHOOK_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      ORDER_SERVICE_URL: http://order-service:8084
      JAVA_TOOL_OPTIONS: "-Xmx130m -Xss256k"

  notification-service:
    image: 980819806799.dkr.ecr.ap-south-1.amazonaws.com/biteloop-notification-service:latest
    container_name: tiffin-notification-service
    depends_on:
      - kafka
    env_file:
      - .env
    mem_limit: 170m
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: ${NOTIFICATION_SERVICE_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      JAVA_TOOL_OPTIONS: "-Xmx120m -Xss256k"